In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('train.csv')
df.head()

,ID,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,...,gender,ethnicity,jaundice,austim,contry_of_res,used_app_before,result,age_desc,relation,Class/ASD
0,1,1,0,1,0,1,0,1,0,1,...,f,?,no,no,Austria,no,6.351166,18 and more,Self,0
1,2,0,0,0,0,0,0,0,0,0,...,m,?,no,no,India,no,2.255185,18 and more,Self,0
2,3,1,1,1,1,1,1,1,1,1,...,m,White-European,no,yes,United States,no,14.851484,18 and more,Self,1
3,4,0,0,0,0,0,0,0,0,0,...,f,?,no,no,United States,no,2.276617,18 and more,Self,0
4,5,0,0,0,0,0,0,0,0,0,...,m,?,no,no,South Africa,no,-4.777286,18 and more,Self,0

In [3]:
df.shape

(800, 22)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               800 non-null    int64
 1   A1_Score         800 non-null    int64
 2   A2_Score         800 non-null    int64
 3   A3_Score         800 non-null    int64
 4   A4_Score         800 non-null    int64
 5   A5_Score         800 non-null    int64
 6   A6_Score         800 non-null    int64
 7   A7_Score         800 non-null    int64
 8   A8_Score         800 non-null    int64
 9   A9_Score         800 non-null    int64
 10  A10_Score        800 non-null    int64
 11  age              800 non-null    float64
 12  gender           800 non-null    str
 13  ethnicity        800 non-null    str
 14  jaundice         800 non-null    str
 15  austim           800 non-null    str
 16  contry_of_res    800 non-null    str
 17  used_app_before  800 non-null    str
 18  result           800 non-null    float64
 19  age_desc         800 non-null    str
 20  relation         800 non-null    str
 21  Class/ASD        800 non-null    int64
dtypes: float64(2), int64(12), str(8)
memory usage: 169.4 KB

In [5]:
df["age"] = df["age"].astype(int)

In [6]:
df.head()

,ID,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,...,gender,ethnicity,jaundice,austim,contry_of_res,used_app_before,result,age_desc,relation,Class/ASD
0,1,1,0,1,0,1,0,1,0,1,...,f,?,no,no,Austria,no,6.351166,18 and more,Self,0
1,2,0,0,0,0,0,0,0,0,0,...,m,?,no,no,India,no,2.255185,18 and more,Self,0
2,3,1,1,1,1,1,1,1,1,1,...,m,White-European,no,yes,United States,no,14.851484,18 and more,Self,1
3,4,0,0,0,0,0,0,0,0,0,...,f,?,no,no,United States,no,2.276617,18 and more,Self,0
4,5,0,0,0,0,0,0,0,0,0,...,m,?,no,no,South Africa,no,-4.777286,18 and more,Self,0

In [7]:
pd.set_option('display.max_columns', None)

In [8]:
df.head()

,ID,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,age,gender,ethnicity,jaundice,austim,contry_of_res,used_app_before,result,age_desc,relation,Class/ASD
0,1,1,0,1,0,1,0,1,0,1,1,38,f,?,no,no,Austria,no,6.351166,18 and more,Self,0
1,2,0,0,0,0,0,0,0,0,0,0,47,m,?,no,no,India,no,2.255185,18 and more,Self,0
2,3,1,1,1,1,1,1,1,1,1,1,7,m,White-European,no,yes,United States,no,14.851484,18 and more,Self,1
3,4,0,0,0,0,0,0,0,0,0,0,23,f,?,no,no,United States,no,2.276617,18 and more,Self,0
4,5,0,0,0,0,0,0,0,0,0,0,43,m,?,no,no,South Africa,no,-4.777286,18 and more,Self,0

In [9]:
for col in df.columns:
    numerical_features = ["ID", "age", "result"]
    if col not in numerical_features:
        print(col, df[col].unique().tolist())
        print("-"*40)

A1_Score [1, 0]
----------------------------------------
A2_Score [0, 1]
----------------------------------------
A3_Score [1, 0]
----------------------------------------
A4_Score [0, 1]
----------------------------------------
A5_Score [1, 0]
----------------------------------------
A6_Score [0, 1]
----------------------------------------
A7_Score [1, 0]
----------------------------------------
A8_Score [0, 1]
----------------------------------------
A9_Score [1, 0]
----------------------------------------
A10_Score [1, 0]
----------------------------------------
gender ['f', 'm']
----------------------------------------
ethnicity ['?', 'White-European', 'Middle Eastern ', 'Pasifika', 'Black', 'Others', 'Hispanic', 'Asian', 'Turkish', 'South Asian', 'Latino', 'others']
----------------------------------------
jaundice ['no', 'yes']
----------------------------------------
austim ['no', 'yes']
----------------------------------------
contry_of_res ['Austria', 'India', 'United States', 'South Africa', 'Jordan', 'United Kingdom', 'Brazil', 'New Zealand', 'Canada', 'Kazakhstan', 'United Arab Emirates', 'Australia', 'Ukraine', 'Iraq', 'France', 'Malaysia', 'Viet Nam', 'Egypt', 'Netherlands', 'Afghanistan', 'Oman', 'Italy', 'AmericanSamoa', 'Bahamas', 'Saudi Arabia', 'Ireland', 'Aruba', 'Sri Lanka', 'Russia', 'Bolivia', 'Azerbaijan', 'Armenia', 'Serbia', 'Ethiopia', 'Sweden', 'Iceland', 'Hong Kong', 'Angola', 'China', 'Germany', 'Spain', 'Tonga', 'Pakistan', 'Iran', 'Argentina', 'Japan', 'Mexico', 'Nicaragua', 'Sierra Leone', 'Czech Republic', 'Niger', 'Romania', 'Cyprus', 'Belgium', 'Burundi', 'Bangladesh']
----------------------------------------
used_app_before ['no', 'yes']
----------------------------------------
age_desc ['18 and more']
----------------------------------------
relation ['Self', 'Relative', 'Parent', '?', 'Others', 'Health care professional']
----------------------------------------
Class/ASD [0, 1]
----------------------------------------

In [10]:
df = df.drop(columns=["ID", "age_desc"])

In [11]:
df.shape

(800, 20)

In [12]:
df.columns

Index(['A1_Score', 'A2_Score', 'A3_Score', 'A4_Score', 'A5_Score', 'A6_Score',
       'A7_Score', 'A8_Score', 'A9_Score', 'A10_Score', 'age', 'gender',
       'ethnicity', 'jaundice', 'austim', 'contry_of_res', 'used_app_before',
       'result', 'relation', 'Class/ASD'],
      dtype='str')

In [13]:
df["contry_of_res"].unique()

<ArrowStringArray>
[             'Austria',                'India',        'United States',
         'South Africa',               'Jordan',       'United Kingdom',
               'Brazil',          'New Zealand',               'Canada',
           'Kazakhstan', 'United Arab Emirates',            'Australia',
              'Ukraine',                 'Iraq',               'France',
             'Malaysia',             'Viet Nam',                'Egypt',
          'Netherlands',          'Afghanistan',                 'Oman',
                'Italy',        'AmericanSamoa',              'Bahamas',
         'Saudi Arabia',              'Ireland',                'Aruba',
            'Sri Lanka',               'Russia',              'Bolivia',
           'Azerbaijan',              'Armenia',               'Serbia',
             'Ethiopia',               'Sweden',              'Iceland',
            'Hong Kong',               'Angola',                'China',
              'Germany',                'Spain',                'Tonga',
             'Pakistan',                 'Iran',            'Argentina',
                'Japan',               'Mexico',            'Nicaragua',
         'Sierra Leone',       'Czech Republic',                'Niger',
              'Romania',               'Cyprus',              'Belgium',
              'Burundi',           'Bangladesh']
Length: 56, dtype: str